-- ============================================================
-- Blueprint DDL — Bupa Health Insurance Claims Processing
-- Generated by bupa-blueprint-app
-- ============================================================

-- Enable pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Table: claim
CREATE TABLE IF NOT EXISTS claim (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    created_by  TEXT,
    -- TODO: add columns specific to Claim
    metadata    JSONB
);

CREATE INDEX IF NOT EXISTS idx_claim_created_at ON claim (created_at);

-- Table: member
CREATE TABLE IF NOT EXISTS member (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    created_by  TEXT,
    -- TODO: add columns specific to Member
    metadata    JSONB
);

CREATE INDEX IF NOT EXISTS idx_member_created_at ON member (created_at);

-- Table: policy
CREATE TABLE IF NOT EXISTS policy (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    created_by  TEXT,
    -- TODO: add columns specific to Policy
    metadata    JSONB
);

CREATE INDEX IF NOT EXISTS idx_policy_created_at ON policy (created_at);

-- Table: provider
CREATE TABLE IF NOT EXISTS provider (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    created_by  TEXT,
    -- TODO: add columns specific to Provider
    metadata    JSONB
);

CREATE INDEX IF NOT EXISTS idx_provider_created_at ON provider (created_at);

-- Table: payment
CREATE TABLE IF NOT EXISTS payment (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
    created_by  TEXT,
    -- TODO: add columns specific to Payment
    metadata    JSONB
);

CREATE INDEX IF NOT EXISTS idx_payment_created_at ON payment (created_at);

-- ============================================================
-- Auto-update updated_at trigger (apply to each table above)
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
