export const HOPEX_REFS = {
  "1.0": "Develop vision and strategy",
  "1.1": "Define the business purpose and long term vision",
  "1.2": "Develop the business strategy",
  "1.2.1": "Develop overall vision statement",
  "1.2.2": "Evaluate strategic options to achieve business objectives",
  "1.2.3": "Conduct organisational restructure opportunities",
  "1.2.4": "Create organisational design (structure, governance, reporting ect.)",
  "1.2.5": "Develop and set organisational goals",
  "1.2.6": "Formulate business unit strategies",
  "1.3": "Manage strategic initiatives",
  "1.3.1": "Develop strategic initiatives",
  "1.3.1.1": "Manage Bupa ANZ Board Activities",
  "1.3.1.2": "Manage Bupa Foundation activities",
  "1.3.2": "Evaluate strategic initiatives",
  "1.3.3": "Select strategic initiatives",
  "1.3.4": "Establish high level measures",
  "1.3.5": "Produce and manage annual operating plan (AOP)",
  "10.0": "Acquire, Build and Manage Assets",
  "10.1": "Plan and aquire assets",
  "10.1.1": "Develop property strategy and long term vision",
  "10.1.2": "Plan facility",
  "10.1.3": "Provide workspace and facilities",
  "10.1.4": "Manage facilities operations",
  "10.2": "Design and construct/acquire non productive assets",
  "10.2.1": "Manage capital program for productive assets",
  "10.2.2": "Design and plan asset construction",
  "10.2.3": "Construct asset",
  "10.2.4": "Maintain asset",
  "10.3": "Obtain and install Health Insurance assets, equipment and tools",
  "10.3.1": "Manage opening of new retail store",
  "10.3.2": "Process and approve new or replacement asset request for Health Insurance",
  "10.4": "Obtain and install Health Services assets and equipment",
  "10.4.1": "Obtain, Install and Manage Health Services assets and equipment",
  "10.4.2": "Repair Health Services assets and equipment",
  "10.4.2.1": "Repair Bupa Dental assets/equipment",
  "10.4.2.2": "Repair Bupa Optical/Hearing assets/equipment",
  "10.4.2.3": "Repair BMVS assets/equipment",
  "10.5": "Obtain and install Bupa Villages and Aged Care (BVAC) assets and equipment",
  "10.5.1": "Manage opening of a new Bupa Village and Aged Care",
  "10.5.2": "Process and approve new or replacement asset request",
  "10.5.3": "Review and maintain assets",
  "10.6": "Dispose of productive and non productive assets",
  "10.6.1": "Manage closure of retail store",
  "10.6.2": "Manage closure or disposal of Health Services assets",
  "10.6.3": "Manage closure of Bupa villages and aged care centre",
  "10.7": "Obtain and install Healthcare Centre assets and equipment",
  "10.7.1": "Acquisition of Healthcare Centre",
  "11.0": "Manage Risk and Compliance",
  "11.1": "Manage enterprise risk",
  "11.1.1": "Establish the enterprise risk framework and policies",
  "11.1.2": "Oversee and coordinate enterprise risk management activities",
  "11.1.3": "Coordinate business unit and functional risk management activities",
  "11.1.4": "Manage business unit and function risk",
  "11.1.4.1": "Manage BVAC risk",
  "11.1.4.2": "Manage Health Services Risk",
  "11.1.4.3": "Manage incidents, policy and risk",
  "11.2": "Manage Compliance",
  "11.2.1": "Establish compliance framework and policies",
  "11.2.2": "Manage regulatory compliance",
  "11.2.3": "Manage Audits",
  "11.2.3.1": "Manage Health Services Audits",
  "11.2.3.2": "Manage BVAC audits",
  "11.2.3.3": "Manage Health Insurance Audits",
  "11.2.3.4": "Manage internal auditing",
  "11.2.4": "Manage insurances, licenses and registration",
  "11.3": "Manage HI Financial Remediation Projects",
  "11.3.1": "Conduct assessment & containment of HI financial remediation projects",
  "11.3.2": "Perform HI financial remediation cohort discovery & treatment planning",
  "11.3.3": "Manage HI financial remediation project readiness activities",
  "11.3.4": "Process & communicate HI financial remediation cases",
  "11.3.5": "Manage HI financial remediation post-resolution activities",
  "11.4": "Manage business resiliency",
  "11.4.1": "Manage business continuity management policy",
  "11.4.2": "Review business continuity process",
  "11.4.2.1": "Review Health Services business continuity process",
  "11.4.3": "Manage business continuity event",
  "11.4.3.2": "Manage Health Services Incident or Emergency",
  "11.4.3.3": "Manage Bupa Villages and Aged Care (BVAC) incident or emergency",
  "11.4.4": "Produce business continuity reporting",
  "11.5": "Manage fraud, abuse and payment integrity",
  "11.5.1": "Develop strategy and monitoring program",
  "11.5.2": "Manage myBupa Suspicious Activities",
  "11.5.3": "Manage Sanction Alerts",
  "11.6": "Manage legal and ethical issues",
  "11.6.1": "Manage corporate governance policies",
  "11.6.2": "Manage outside counsel",
  "11.6.3": "Resolve disputes and litigations",
  "11.6.4": "Provide legal advice/counseling",
  "11.6.5": "Negotiate and document agreements/contracts",
  "11.7": "Manage quality and compliance checking",
  "11.7.1": "Create and manage quality and compliance strategy",
  "11.7.1.1": "Create and manage Health Services Quality and Compliance Strategy",
  "11.7.2": "Benchmark quality",
  "11.7.2.1": "Benchmark Health Services quality",
  "11.7.3": "Evaluate quality performance",
  "11.7.4": "Manage BVAC AU Quality and Compliance",
  "11.8": "Manage Risks and Workplace Health and Safety",
  "11.8.1": "Conduct assessments & checks",
  "11.8.2": "Manage first aid",
  "11.8.3": "Manage Hazards (Electrical, slips, trips, falls, ladders)",
  "11.8.4": "Manage Occupational Health and Safety (OHS)",
  "11.9": "Manage environmental health and safety (EHS)",
  "11.9.1": "Determine environmental health and safety impacts",
  "11.9.2": "Develop and execute functional EHS program",
  "11.9.3": "Train and educate functional employees",
  "11.9.4": "Monitor and manage functional EHS management program",
  "12.0": "Manage external & regulatory relationships",
  "12.1": "Manage public relations",
  "12.1.1": "Manage community relations",
  "12.1.2": "Manage media relations",
  "12.1.3": "Promote political stability",
  "12.1.4": "Create press releases",
  "12.1.5": "Issue press releases",
  "12.1.6": "Manage public policy submissions",
  "12.2": "Manage relations with wider Bupa",
  "12.2.1": "Manage global change",
  "12.2.2": "Communicate global changes",
  "12.3": "Manage government and industry relationships",
  "12.3.1": "Manage government relations",
  "12.3.2": "Manage relations with quasi-government bodies",
  "12.3.3": "Manage relations with trade or industry groups",
  "12.3.4": "Manage lobby activities",
  "12.3.5": "Manage government review",
  "12.3.6": "Manage Clinical Relations",
  "13.0": "Manage and Deliver Change",
  "13.1": "Measure and benchmark",
  "13.1.1": "Create and manage organizational performance strategy",
  "13.1.2": "Benchmark performance",
  "13.1.3": "Evaluate process performance",
  "13.2": "Manage portfolios, programmes and projects",
  "13.2.1": "Manage projects and initiatives",
  "13.2.1.1": "Identify projects or initiatives and secure funding",
  "13.2.1.2": "Develop HI projects and initiatives",
  "13.2.2": "Finalise and deploy project or proposition",
  "13.3": "Manage Testing",
  "13.3.1": "Plan & Execute Testing",
  "13.4": "Manage Change",
  "13.4.1": "Manage business readiness",
  "13.4.2": "Conduct close-down and PIR activities",
  "13.4.3": "Manage Bupa Dental Digital Content",
  "13.5": "Manage Knowledge and Learning artefacts",
  "13.5.1": "Manage knowledge content and functionality creation",
  "13.5.2": "Manage creation of learning artefacts",
  "13.5.3": "Manage Workvivo content",
  "13.6": "Manage business processes",
  "13.6.1": "Establish and maintain process management governance",
  "13.6.2": "Define and manage process frameworks",
  "13.6.3": "Define processes",
  "13.6.4": "Manage process performance",
  "13.6.5": "Improve processes",
  "2.0": "Develop and Manage Propositions",
  "2.1": "Develop policies",
  "2.1.1": "Develop Fund rules",
  "2.1.2": "Monitor policy rules adherence",
  "2.1.4": "Develop healthcare management policy, planning and strategy",
  "2.2": "Develop propositions",
  "2.2.1": "Develop a Health Insurance proposition",
  "2.2.1.1": "Define, approve & deliver a Health Insurance proposition",
  "2.2.1.2": "Manufacture a Health Insurance proposition",
  "2.2.1.3": "Retire or withdraw existing HI proposition",
  "2.2.2": "Develop Health Services proposition",
  "2.2.3": "Develop Bupa Villages and Aged Care proposition",
  "2.3": "Manage propositions",
  "2.3.1": "Evaluate Health Insurance propositions and performance",
  "2.3.1.1": "Conduct portfolio performance & commercial analysis",
  "2.3.1.2": "Conduct healthcare program proposition analysis",
  "2.3.1.3": "Conduct competitor analysis",
  "2.3.1.4": "Seek customer insights (Placeholder)-1",
  "2.3.1.5": "Conduct clinical analysis",
  "2.3.2": "Manage annual Health Insurance changes to portfolio",
  "2.3.3": "Manage Health Insurance regulatory proposition documents",
  "2.3.4": "Manage Health Services proposition",
  "2.3.5": "Manage Bupa Villages and Aged Care (BVAC) proposition",
  "2.4": "Determine & manage items & benefits",
  "2.4.1": "Provide item & benefit administration",
  "3.0": "Market Products and Services",
  "3.1": "Understand markets, customers and capabilities",
  "3.1.1": "Perform customer and market intelligence analysis",
  "3.2": "Develop marketing strategy",
  "3.2.1": "Define customer value proposition",
  "3.2.2": "Define pricing strategy to align to value proposition",
  "3.2.3": "Define and manage channel strategy",
  "3.2.5": "Prepare Marketing Offerings and Timings",
  "3.3": "Develop and manage marketing campaigns and material",
  "3.3.1": "Develop campaign brief and marketing materials",
  "3.3.1.1": "Create campaign brief and marketing materials",
  "3.3.2": "Conduct sign off of material",
  "3.3.3": "Prepare for launch of campaign",
  "3.3.3.1": "Prepare for launch of HI campaign",
  "3.4": "Execute marketing activities",
  "3.4.1": "Launch marketing campaign or communications",
  "3.4.2": "Monitor and manage campaign activities",
  "3.4.3": "Close campaign",
  "4.0": "Sell products & services",
  "4.1": "Develop sales distribution strategy",
  "4.1.1": "Develop overall sales targets",
  "4.1.2": "Develop distribution strategy",
  "4.1.3": "Manage sales resources",
  "4.1.4": "Create & monitor metrics & measures",
  "4.1.4.1": "Create & monitor sales metric measures (HI)",
  "4.1.4.2": "Create & monitor Health Services metrics & volumes",
  "4.2": "Deliver sales distribution strategy",
  "4.2.1": "Deliver retail sales strategy",
  "4.2.1.1": "Generate corporate sales leads",
  "4.2.2": "Deliver business-to-business (B2B) sales",
  "4.2.2.1": "Manage new business & onboarding",
  "4.2.2.2": "Manage account relationships",
  "4.2.2.3": "Manage commission payments & system administration",
  "4.2.2.4": "Manage wellness/excess pools",
  "4.2.2.5": "Manage direct business & customer success",
  "4.2.3": "Deliver online sales",
  "4.2.4": "Deliver partnership sales",
  "4.2.5": "Deliver general insurance sales strategy",
  "4.3": "Sell insurance",
  "4.3.1": "Sell Health Insurance",
  "4.3.1.1": "Manage new business enquiries, leads & applications",
  "4.3.1.2": "Manage new business quotes",
  "4.3.1.3": "Manage new business enrolments",
  "4.3.1.4": "Follow up leads/prospects",
  "4.3.1.5": "Complete sales fulfilment",
  "4.3.2": "Sell financial services insurance",
  "4.4": "Sell health, wellness & care services",
  "4.4.1": "Sell wellness programs",
  "4.4.1.1": "Conduct quote for wellness service",
  "4.4.2": "Sell care services",
  "4.5": "Sell Bupa Optical & Hearing products",
  "4.5.1": "Manage & sell new optical product offerings",
  "4.5.2": "Raise new Bupa Optical customer order",
  "4.6": "Sell Bupa Villages & Aged Care (BVAC) services",
  "4.6.1": "Manage aged care enquiries & applications",
  "4.6.1.1": "Manage BVAC AU aged care enquiry",
  "4.6.1.2": "Manage BVAC AU admission suitability",
  "4.6.2": "Manage Retirement enquiries & applications",
  "4.6.3": "Manage BVAC agreements & financials",
  "5.0": "Deliver products & services",
  "5.1": "Manage 3rd party relationships",
  "5.1.1": "Manage 3rd party contracts",
  "5.1.1.1": "Manage hospital & medical contracts",
  "5.1.1.2": "Manage ancillary provider contracts",
  "5.1.1.3": "Manage corporate client agreements",
  "5.1.1.4": "Manage health program & partnership contracts",
  "5.1.1.5": "Manage Bupa Dental suppliers",
  "5.1.1.6": "Manage Bupa Optical/Hearing suppliers & providers",
  "5.1.1.7": "Manage Bupa Medical Visa Services 3rd party suppliers",
  "5.1.1.8": "Manage Bupa Villages & Aged Care 3rd parties",
  "5.1.1.9": "Manage Loyalty Rewards contracts",
  "5.1.2": "Manage provider details",
  "5.1.2.1": "Perform provider related system maintenance",
  "5.1.2.2": "Maintain health program providers",
  "5.1.2.3": "Manage Bupa dental provider & supplier details",
  "5.1.2.4": "Manage Bupa Optical/Hearing provider & supplier details",
  "5.1.2.5": "Manage BMVS Provider & supplier details",
  "5.1.2.6": "Manage BVAC provider details",
  "5.1.2.7": "Manage Healthcare centres provider/practitioner details",
  "5.1.3": "Review provider performance",
  "5.10": "Deliver BVAC Medical and Wellbeing Centre services",
  "5.10.1": "Manage BVAC enquiries and bookings for medical and wellbeing centre",
  "5.10.2": "Deliver BVAC treatment in medical and wellbeing centre",
  "5.10.3": "Manage BVAC medication and treatments",
  "5.10.4": "Manage BVAC incidents and infection control",
  "5.10.5": "Manage BVAC payments and claiming",
  "5.11": "Deliver loyalty rewards",
  "5.11.1": "Deliver health insurance loyalty program",
  "5.13": "Deliver net promoter score (NPS)",
  "5.13.1": "Deliver MBS net promoter score surveys",
  "5.13.1.1": "Develop & approve MBS net promoter score surveys",
  "5.13.1.2": "Manage MBS net promoter score survey distribution",
  "5.13.2": "Deliver non-MBS net promoter score surveys",
  "5.13.3": "Perform net promoter score analysis, reporting & oversight",
  "5.13.3.1": "Perform net promoter score analysis",
  "5.13.3.2": "Manage net promoter score reporting & oversight",
  "5.2": "Manage health & care delivery",
  "5.2.1": "Manage provider enquiries",
  "5.2.1.1": "Manage provider/organisations details",
  "5.2.1.2": "Manage provider statement enquiries",
  "5.2.1.3": "Manage provider claims",
  "5.2.1.4": "Support provider enquiries",
  "5.3": "Deliver insurance claim assessment",
  "5.3.1": "Receive claim or entitlement request",
  "5.3.2": "Perform entitlement check",
  "5.3.2.1": "Perform eligibility checks",
  "5.3.2.2": "Manage benefit entitlements",
  "5.3.2.3": "Manage pre approval requests",
  "5.3.2.4": "Manage certificates/forms",
  "5.3.2.5": "Manage repatriation approval & claim",
  "5.3.3": "Assess claim",
  "5.3.3.1": "Assess hospital claim",
  "5.3.3.2": "Assess medical claim",
  "5.3.3.3": "Assess extras claims",
  "5.3.4": "Review claim",
  "5.3.4.1": "Review hospital claim",
  "5.3.4.2": "Review medical claim",
  "5.3.4.3": "Review extras claim",
  "5.3.5": "Process benefit payments",
  "5.3.6": "Communicate claims related outcome",
  "5.3.6.1": "Communicate hospital claim outcome",
  "5.3.6.2": "Communicate medical claim outcome",
  "5.3.6.3": "Communicate extras claim outcome",
  "5.3.7": "Manage claims integrity and recoveries",
  "5.3.7.1": "Manage claims integrity",
  "5.3.7.2": "Manage claims recoveries",
  "5.4": "Deliver health, wellness & care services",
  "5.4.1": "Identifying the targeted customer",
  "5.4.1.1": "Generate reports to identify potential customers",
  "5.4.1.2": "Manage expression of interest (EOI) and referrals",
  "5.4.1.3": "Identify eligible customers for healthcare programs",
  "5.4.2": "Manage preparation activities",
  "5.4.2.1": "Manage allocated calls & follow ups",
  "5.4.2.2": "Schedule wellness jobs",
  "5.4.2.3": "Manage wellness bookings & cancellations",
  "5.4.2.4": "Prepare for wellness job",
  "5.4.2.5": "Manage wellness supplies",
  "5.4.3": "Deliver coaching and wellness services",
  "5.4.3.1": "Deliver phone coaching services",
  "5.4.3.2": "Deliver wellness service",
  "5.4.3.3": "Fulfill communications",
  "5.4.4": "Conduct post delivery activities",
  "5.4.4.1": "Conduct and manage customer satisfaction",
  "5.4.4.2": "Manage wellness incidents and assessments",
  "5.4.4.3": "Manage wellness administration",
  "5.4.4.4": "Manage healthcare incidents & complaints",
  "5.4.5": "Generate health & care reports",
  "5.5": "Deliver general insurance services",
  "5.5.1": "Receive general insurance enquiry",
  "5.6": "Deliver Bupa Dental Services",
  "5.6.1": "Prepare dental practice",
  "5.6.1.1": "Manage dental supply orders",
  "5.6.1.2": "Prepare dental environment",
  "5.6.1.3": "Manage & control infection for dental practice",
  "5.6.1.4": "Manage radiation equipment in dental practice",
  "5.6.2": "Receive dental patient for care",
  "5.6.2.1": "Manage dental patient appointments",
  "5.6.2.2": "Manage dental patient information",
  "5.6.3": "Deliver dental treatment",
  "5.6.3.1": "Administer dental treatment",
  "5.6.3.2": "Manage dental incidents and injury",
  "5.6.4": "Manage and Check out Dental Patient (Post Treatment)",
  "5.7": "Deliver Bupa Optical and Hearing Services",
  "5.7.1": "Prepare Bupa Optical/Hearing store",
  "5.7.1.1": "Manage Optical/Hearing store supply orders and administration",
  "5.7.1.2": "Prepare Bupa Optical/Hearing store environment and merchandise",
  "5.7.1.3": "Manage Infection Control and Prevention in Bupa Optical/Hearing store",
  "5.7.1.4": "Manage Medication in Bupa Optical/Hearing store",
  "5.7.1.5": "Perform Bupa Optical/Hearing Store Operating Activities",
  "5.7.2": "Manage Bupa Optical/Hearing Stock",
  "5.7.2.1": "Order and manage Bupa Optical/Hearing store stock",
  "5.7.2.2": "Manage Bupa Optical/Hearing stock transfers and returns",
  "5.7.3": "Receive customer/patient visit to Bupa Optical and Hearing",
  "5.7.3.1": "Manage Optical and Hearing Bookings",
  "5.7.3.2": "Receive Bupa Optical/Hearing customer/patient instore",
  "5.7.4": "Deliver Bupa Optical/Hearing Services",
  "5.7.4.1": "Deliver Bupa optical consult",
  "5.7.4.2": "Deliver Bupa hearing consult",
  "5.7.4.3": "Manage Bupa Optical/Hearing incidents/injury",
  "5.7.5": "Manage Bupa Optical/Hearing customer orders",
  "5.7.5.1": "Receive Bupa Optical/Hearing Customer Order instore",
  "5.7.5.2": "Manage Bupa Optical/Hearing Customer Order collection",
  "5.8": "Deliver BMVS Services",
  "5.8.1": "Prepare BMVS Clinic and Equipment",
  "5.8.1.1": "Prepare Clinic and Equipment",
  "5.8.1.2": "Manage and Control Infection",
  "5.8.1.3": "Perform Clinic Operating Activities",
  "5.8.1.4": "Manage supporting Services",
  "5.8.2": "Manage BMVS Booking Enquiries and Arrivals",
  "5.8.3": "Conduct BMVS concierge & reception activities",
  "5.8.3.1": "Receive patient & conduct checks (BMVS)",
  "5.8.3.2": "Take BMVS customer payment",
  "5.8.4": "Deliver Medical Visa Assessments",
  "5.8.4.1": "Prepare and Commence Medical Assessment",
  "5.8.4.2": "Conduct Medical Assessment",
  "5.8.4.3": "Determine Medical Assessment Outcome",
  "5.8.4.4": "Manage Referrals and Followups",
  "5.8.4.5": "Conduct Post Assessment Activities",
  "5.8.4.6": "Manage Incidents and Injury",
  "5.9": "Deliver Bupa Villages and Aged Care services (BVAC)",
  "5.9.1": "Manage BVAC admissions",
  "5.9.1.1": "Manage BVAC retirement village admissions",
  "5.9.1.2": "Manage BVAC AU care home admission",
  "5.9.1.3": "Manage BVAC consent and information",
  "5.9.2": "Manage BVAC assessments and clinical/medical services",
  "5.9.2.1": "Assist a BVAC AU Resident to Settle In",
  "5.9.2.2": "Assist a BVAC NZ Resident to Settle In",
  "5.9.3": "Manage BVAC activities of daily living",
  "5.9.3.1": "Manage BVAC AU Activities of Daily Living",
  "5.9.3.2": "Manage BVAC NZ Activities of Daily Living",
  "5.9.4": "Manage BVAC medications",
  "5.9.4.1": "Manage BVAC AU Medications",
  "5.9.4.2": "Manage BVAC NZ Medications",
  "5.9.5": "Manage BVAC Clinical Health Care",
  "5.9.5.1": "Manage BVAC AU Clinical Health Care",
  "5.9.6": "Manage BVAC infection control",
  "5.9.6.1": "Manage Infection Control for BVAC AU",
  "5.9.6.2": "Manage Infection Control for BVAC NZ",
  "5.9.7": "Manage BVAC Incidents",
  "5.9.7.1": "Manage a BVAC AU Incident",
  "5.9.7.2": "Manage a BVAC NZ Incident",
  "5.9.8": "Manage BVAC resident/client departure",
  "5.9.8.1": "Manage a BVAC AU Resident Departure",
  "5.9.8.2": "Manage a BVAC NZ Resident Departure",
  "5.9.9": "Manage BVAC supporting services",
  "5.9.9.2": "Manage Cleaning Services",
  "5.9.9.4": "Manage Waste Services",
  "5.9.9.7": "Manage Maintenance",
  "5.9.9.8": "Manage Care Home Administration",
  "6.0": "Service customers",
  "6.1": "Develop service operating model",
  "6.1.1": "Define servicing policies and procedures",
  "6.1.2": "Establish service level agreements",
  "6.1.3": "Plan and manage service workforce",
  "6.1.3.1": "Plan and manage Health Services workforce",
  "6.1.3.2": "Plan and manage Bupa Villages and Aged Care workforce",
  "6.2": "Manage Health Insurance policy information",
  "6.2.1": "Manage inbound service requests",
  "6.2.2": "Manage customer details",
  "6.2.3": "Manage policy maintenance",
  "6.2.3.1": "Change policy information",
  "6.2.3.2": "Update policy information",
  "6.2.4": "Manage legislative selections",
  "6.2.4.1": "Manage Australian government private health insurance rebate",
  "6.2.4.2": "Manage clearance, portability, lifetime health cover loading, & age-based discount",
  "6.2.5": "Manage billing & payment support processes",
  "6.2.5.1": "Manage billing & payments",
  "6.2.5.2": "Generate & apply corporate bills",
  "6.2.5.3": "Manage corporate billing adjustments",
  "6.2.5.4": "Manage refunds",
  "6.2.5.5": "Manage dishonours & arrears",
  "6.2.5.6": "Manage payment errors",
  "6.2.6": "Manage customer complaints/disputes (HI)",
  "6.2.7": "Manage policy cancellations & offboarding",
  "6.2.8": "Manage outbound policy communications",
  "6.2.8.1": "Request & fulfil communications",
  "6.2.8.2": "Generate communication files",
  "6.2.8.3": "Support generation of communications",
  "6.2.9": "Manage policy reports",
  "6.2.9.1": "Manage claim reports",
  "6.2.9.2": "Manage payment & policy reports",
  "6.3": "Manage General Insurance policy information",
  "6.3.1": "Manage General Insurance Customer Information and Preferences",
  "6.3.2": "Manage General Insurance customer complaints",
  "6.4": "Manage Bupa Dental information",
  "6.4.1": "Manage dental patient billing and payment support processes",
  "6.4.1.1": "Manage claiming",
  "6.4.1.2": "Manage patient payments",
  "6.4.1.3": "Manage patient payment reconciliations",
  "6.4.2": "Manage dental patient feedback & complaints",
  "6.4.3": "Manage medical documentation",
  "6.5": "Manage Bupa Optical and Hearing information",
  "6.5.1": "Manage patient details (OpHear)",
  "6.5.2": "Manage patient referrals (OpHear)",
  "6.5.3": "Manage patient billing and payment supporting processes (OpHear)",
  "6.5.3.1": "Manage Bupa Optical and Hearing patient payments",
  "6.5.3.2": "Manage Bupa Optical and Hearing claiming",
  "6.5.3.3": "Manage Bupa Optical and Hearing payment reporting",
  "6.5.4": "Manage Bupa Optical and Hearing feedback and complaints",
  "6.5.5": "Manage medical documentation (OpHear)",
  "6.5.6": "Manage Bupa Optical and Hearing Return or Repair",
  "6.6": "Manage Bupa Medical and Visa Services information",
  "6.6.1": "Manage inbound BMVS cases and requests",
  "6.6.2": "Manage BMVS case enquiries",
  "6.6.3": "Manage BMVS customer details",
  "6.6.4": "Manage BMVS Payment Support Processes",
  "6.6.4.1": "Manage BMVS Payment Invoices",
  "6.6.4.2": "Manage BMVS Payment Reporting",
  "6.6.4.3": "Manage BMVS payment refunds and transfers",
  "6.6.5": "Manage BMVS medical documentation",
  "6.6.7": "Manage outbound case communications",
  "6.7": "Manage Bupa Villages and Aged Care information",
  "6.7.1": "Manage BVAC billing and payment processes",
  "6.7.2": "Manage and aquire BVAC equipment",
  "6.7.3": "Manage BVAC complaints and customer satisfaction",
  "6.7.3.1": "Manage BVAC complaints",
  "6.7.3.2": "Manage Continuous Improvements in BVAC",
  "6.7.4": "Manage BVAC documents and archiving",
  "6.8": "Manage healthcare centres information",
  "6.8.1": "Manage healthcare centre claiming",
  "6.8.2": "Manage Healthcare Centre payments",
  "6.8.3": "Manage Healthcare Centre billing and reconciliation",
  "6.8.4": "Manage Healthcare Centre complaints and detractors",
  "6.8.5": "Manage Healthcare Centre documents & archiving",
  "6.9": "Manage healthcare & wellness information",
  "6.9.1": "Manage wellness job queries",
  "7.0": "Develop and Manage People and Culture",
  "7.1": "Manage recruitment & onboarding",
  "7.1.1": "Manage position description, job requisition and postings",
  "7.1.2": "Manage sourcing and interviews",
  "7.1.3": "Manage candidate background checks",
  "7.1.4": "Generate employment contracts and finalise offer",
  "7.1.5": "Manage onboarding and commencement",
  "7.2": "Manage employment",
  "7.2.1": "Manage changes to current role or position",
  "7.2.2": "Manage employee position changes",
  "7.2.3": "Manage Employee Security, System Access & Administration",
  "7.2.4": "Manage employee details",
  "7.2.5": "Manage Shifts, Timesheets and Invoices",
  "7.2.6": "Manage employee leave",
  "7.2.7": "Manage restructure",
  "7.3": "Manage remuneration and reward",
  "7.3.1": "Manage awards, rates & ranges",
  "7.3.2": "Manage rewards & Incentives for employees",
  "7.3.3": "Manage referral programmes",
  "7.4": "Manage performance & development",
  "7.4.1": "Prepare & manage annual review",
  "7.4.2": "Manage employee performance & development",
  "7.5": "Manage training & additional learning",
  "7.5.1": "Create learning materials",
  "7.5.2": "Manage existing modules",
  "7.6": "Manage people incidents, compliance & risk",
  "7.6.1": "Manage people incidents, risk & compliance",
  "7.6.2": "Manage employee investigations & escalations",
  "7.6.3": "Manage employee assistance",
  "7.6.4": "Manage union enquiries",
  "7.6.5": "Manage system and data audits",
  "7.7": "Manage end of employment",
  "7.7.1": "Manage termination",
  "7.7.2": "Manage end of employment circumstance",
  "7.8": "Manage People Processes and Systems",
  "7.8.1": "Manage People Process Maps",
  "7.8.2": "Manage People Systems",
  "7.8.3": "Manage People Dimensions Support",
  "7.8.4": "Manage BESS tickets for Dimensions",
  "7.8.5": "Manage people system vendors",
  "8.0": "Manage Technology",
  "8.1": "Manage the business of information systems",
  "8.1.1": "Manage the business of information systems",
  "8.1.2": "Define enterprise architecture",
  "8.1.3": "Manage Technology portfolio",
  "8.1.4": "Perform Technology research and innovation",
  "8.1.5": "Evaluate and communicate Technology business value and performance",
  "8.2": "Develop and manage Technology customer relationships",
  "8.2.1": "Develop Technology services and solutions strategy",
  "8.2.2": "Develop and manage Technology service levels",
  "8.2.3": "Perform demand site management for Technology services",
  "8.2.4": "Manage Technology customer satisfaction",
  "8.2.5": "Market Technology services and solutions",
  "8.3": "Develop and implement security, private and data protection controls",
  "8.3.1": "Establish information security, privacy & data protection controls",
  "8.3.2": "Test, evaluate & implement information security & privacy of data protection controls",
  "8.4": "Manage enterprise information",
  "8.4.1": "Perform EDI management",
  "8.4.2": "Perform provider infomatics",
  "8.4.3": "Develop and maintain product informatics/reporting",
  "8.4.4": "Set up membership accounts analytics",
  "8.4.5": "Develop information and content management strategies",
  "8.4.6": "Define the enterprise information architecture",
  "8.4.7": "Manage information resources",
  "8.4.8": "Perform enterprise data and content management",
  "8.4.8.1": "Manage content delivery and web application firewall",
  "8.5": "Develop and maintain information technology solutions",
  "8.5.1": "Develop the Technology development strategy",
  "8.5.2": "Perform Technology services and solutions life cycle planning",
  "8.5.3": "Develop and maintain Technology services and solutions architecture",
  "8.5.4": "Create Technology services and solutions",
  "8.5.5": "Maintain Technology services and solutions",
  "8.6": "Develop information technology solutions",
  "8.6.1": "Develop the Technology deployment strategy",
  "8.6.2": "Plan and implement changes",
  "8.6.3": "Create and maintain technology change approval",
  "8.6.4": "Plan and manage releases",
  "8.7": "Deliver and support information technology services",
  "8.7.1": "Develop Technology services and solution delivery strategy",
  "8.7.2": "Develop Technology support strategy",
  "8.7.3": "Manage Technology infrastructure resources",
  "8.7.4": "Manage Technology infrastructure operations",
  "8.7.5": "Identify and manage technology incidents",
  "9.0": "Manage financial resources",
  "9.1": "Perform financial strategy & planning",
  "9.1.1": "Perform planning, budgeting & forecasting on financial performance",
  "9.1.1.1": "Perform planning, budgeting & forecasting",
  "9.1.1.2": "Evaluate and manage financial performance",
  "9.1.2": "Manage commercial modelling and budgeting",
  "9.1.3": "Manage mergers and acquisitions",
  "9.1.4": "Manage environment and climate action forcasting and support",
  "9.10": "Perform financial control",
  "9.10.1": "Manage financial control policies and procedures",
  "9.10.10": "Perform ESG Reporting",
  "9.10.11": "Perform financial control supporting processes",
  "9.10.12": "Perform Modelling Governance Procedures",
  "9.10.2": "Perform general accounting",
  "9.10.2.1": "Perform general accounting for Health Insurance",
  "9.10.2.2": "Perform general accounting for Health Services",
  "9.10.2.3": "Perform general accounting for Bupa Villages and Aged Care (BVAC)",
  "9.10.3": "Perform financial reporting",
  "9.10.4": "Perform Regulatory Business Reporting",
  "9.10.5": "Conduct Financial Statement close for business unit's",
  "9.10.6": "Conduct balance sheet reconciliations",
  "9.10.7": "Perform property valuations",
  "9.10.8": "Perform goodwill impairment testing",
  "9.10.9": "Manage financial crime risk",
  "9.2": "Manage treasury functions",
  "9.2.1": "Manage investments/ international funds/consolidations",
  "9.2.1.1": "Monitor international rates",
  "9.2.1.2": "Manage transactions",
  "9.2.1.4": "Report results",
  "9.2.1.5": "Manage financial control investments",
  "9.2.3": "Manage credits & loans",
  "9.2.6": "Monitor & execute risk & hedging transactions",
  "9.2.7": "Manage counterparty risk management",
  "9.2.7.1": "Conduct debtors counterparty risk management (ANZ)",
  "9.2.7.2": "Conduct debtors counterparty risk management (HK)",
  "9.2.8": "Manage liquidity (including dividend/repatriation management)",
  "9.3": "Conduct actuarial services",
  "9.3.1": "Manage actuarial provisioning",
  "9.3.2": "Manage actuarial reporting",
  "9.4": "Conduct procurement and supplier management",
  "9.4.1": "Manage sourcing and procurement strategy and planning",
  "9.4.2": "Manage procurement suppliers",
  "9.4.3": "Conduct procurement",
  "9.4.4": "Finalise Procurement Invoicing & Reporting",
  "9.5": "Manage banking operations",
  "9.5.1": "Manage banking operation policies & procedures",
  "9.5.2": "Manage banking and supplier setup",
  "9.5.3": "Manage cash & banking",
  "9.5.3.1": "Manage HI cash and daily banking",
  "9.5.3.2": "Manage HI cashbox",
  "9.5.3.3": "Manage HS daily cash and banking",
  "9.5.3.4": "Manage BVAC daily cash & banking",
  "9.5.4": "Manage in-house bank accounts",
  "9.6": "Manage accounts receiveable",
  "9.6.1": "Manage invoices",
  "9.6.1.1": "Manage general invoices",
  "9.6.1.2": "Manage HI invoices",
  "9.6.1.3": "Manage HS invoices",
  "9.6.1.4": "Manage BVAC invoices",
  "9.6.2": "Process accounts receivable (AR)",
  "9.6.2.1": "Manage general accounts receivable",
  "9.6.2.2": "Process HI accounts receivable",
  "9.6.2.3": "Process HS accounts receivable",
  "9.6.2.4": "Process BVAC AU accounts receivable",
  "9.6.2.5": "Process BVAC NZ accounts receivable",
  "9.6.3": "Manage debt and collections",
  "9.6.3.1": "Manage general debt and collections",
  "9.6.3.2": "Manage HI debt and collections",
  "9.6.3.3": "Manage HS debt and collections",
  "9.6.3.4": "Manage BVAC AU debt and collections",
  "9.6.3.5": "Manage BVAC NZ debt and collections",
  "9.6.4": "Manage and process adjustments and deductions",
  "9.6.4.1": "Manage and process general adjustments/deductions",
  "9.6.4.2": "Manage and process HI adjustments/deductions",
  "9.6.4.3": "Manage and process HS adjustments/deductions",
  "9.6.4.4": "Manage & process BVAC adjustments/deductions",
  "9.7": "Manage accounts payable and expense reimbursements",
  "9.7.1": "Manage preferred suppliers for expenses",
  "9.7.1.1": "Manage general preferred suppliers for expenses",
  "9.7.1.2": "Manage HI preferred suppliers for expenses",
  "9.7.1.3": "Manage HS preferred suppliers for expenses",
  "9.7.1.4": "Manage BVAC preferred suppliers for expenses",
  "9.7.2": "Process accounts payable (AP)",
  "9.7.2.1": "Process general accounts payable (AP)",
  "9.7.2.2": "Process HI accounts payable",
  "9.7.2.3": "Process HS accounts payable",
  "9.7.2.4": "Process BVAC accounts payable",
  "9.7.3": "Process expense reimbursements",
  "9.7.3.1": "Raise expense request",
  "9.7.3.2": "Manage and approve expense request",
  "9.7.4": "Manage corporate credit cards & card policy",
  "9.7.5": "Run accounts & expense reporting",
  "9.7.5.1": "Run general accounts & expense reporting",
  "9.7.5.2": "Run HI general accounts & expense reporting",
  "9.7.5.3": "Run HS general accounts & expense reporting",
  "9.7.5.4": "Run BVAC general accounts & expense reporting",
  "9.8": "Process payroll",
  "9.8.1": "Manage Payroll Employee Information",
  "9.8.2": "Manage Payroll and Leave Information",
  "9.8.3": "Conduct Pay Run",
  "9.8.4": "Process payroll taxes and reporting",
  "9.9": "Manage taxes",
  "9.9.1": "Develop tax strategy and plan",
  "9.9.2": "Process taxes",
  "9.9.2.1": "Process tax calculations and payments",
  "9.9.2.2": "Perform HK tax processes",
  "9.9.2.3": "Produce tax reporting"
} ;
